### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by alicejeeunlee** [alicejeeunlee/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Make data model to track direction that car is facing
- [x] Style CSS class to match direction 
- [x] Listen for key down events on document
