### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by alicejeeunlee** [alicejeeunlee/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add boolean to data model to check whether if car was started
- [x] Add function to stop car
- [x] Clear interval if boolean is false
